---
- name: Deploy matjb.dev
  hosts: all
  remote_user: matej
  vars:
    clone_dir: /home/matej/matjb.dev
    deploy_dir: /var/www/matjb.dev

  tasks:
    - name: Clone git repo
      ansible.builtin.git:
        repo: git@github.com:matejbuocik/matjb.dev.git
        dest: '{{ clone_dir }}'
        single_branch: true
        version: main
        depth: 1

    - name: Copy www to deploy dir
      ansible.builtin.copy:
        src: '{{ clone_dir }}/www/'
        dest: '{{ deploy_dir }}'
        mode: preserve
        remote_src: true

    - name: Remove cloned repo
      ansible.builtin.file:
        path: '{{ clone_dir }}'
        state: absent

    - name: Check that nginx is running
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true
